[tool.poetry]
name = "theburgbot"
version = "0.1.0"
description = ""
authors = ["Ryan Joseph <ryan@electricsheep.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
